/*
------------------------------------------------------------------------------
QUESTION
------------------------------------------------------------------------------
For each month in 2024, compute the total revenue generated by the "Electronics" category.
Return: month, total_revenue.

------------------------------------------------------------------------------
SCHEMA
------------------------------------------------------------------------------
orders(order_id, customer_id, order_date, total_amount)
order_items(order_item_id, order_id, product_id, quantity, price_per_unit)
products(product_id, category, product_name)

*/
SELECT
    EXTRACT(MONTH FROM o.order_date) AS month,
    SUM(i.quantity * i.price_per_unit) AS total_revenue
FROM
    orders o
    JOIN order_items i ON o.order_id = i.order_id
    JOIN products p ON i.product_id = p.product_id
WHERE
    p.category = 'Electronics'
    AND EXTRACT(YEAR FROM o.order_date) = 2024
GROUP BY
    EXTRACT(MONTH FROM o.order_date)
ORDER BY
    month;
